TEXT_FIELDS = '//input[@type="text"]'
NEXT_BUTTON = '//div[@jsname="OCpkoe"]'
SUBMIT_BUTTON = '//div[@jsname="M2UYVd"]'
DROPDOWN_MENU = '//div[@role="listbox"]'
PARENTS_INFO = '//input[@type="text"]'
